/*
 * JS for about generated by Exadel Tiggzi
 *
 * Created on: Wednesday, December 12, 2012, 02:14:38 AM (PST)
 */
/************************************
 * JS API provided by Exadel Tiggzi  *
 ************************************/
/* Setting project environment indicator */
Tiggr.env = "bundle";
Tiggr.getProjectGUID = function() {
    return 'f72a02e6-a853-43f7-a85d-9ec687e00db1';
}
Tiggr.getTargetPlatform = function() {
    return '0';
}

function navigateTo(outcome, useAjax) {
    Tiggr.navigateTo(outcome, useAjax);
}

function adjustContentHeight() {
    Tiggr.adjustContentHeight();
}

function adjustContentHeightWithPadding() {
    Tiggr.adjustContentHeightWithPadding();
}

function setDetailContent(pageUrl) {
    Tiggr.setDetailContent(pageUrl);
}
/**********************
 * SECURITY CONTEXTS  *
 **********************/
/*******************************
 *      SERVICE SETTINGS        *
 ********************************/
/*************************
 *      SERVICES          *
 *************************/
createSpinner("files/resources/lib/jquerymobile/images/ajax-loader.gif");
Tiggr.AppPages = [{
    "name": "startScreen",
    "location": "startScreen.html"
}, {
    "name": "about",
    "location": "about.html"
}, {
    "name": "twitter",
    "location": "twitter.html"
}, {
  "name": "rss",
	"location": "rss.html"
}];
j_15_js = function(runBeforeShow) { /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'navbar1': 'j_18',
        'homeicon1': 'j_19',
        'twittericon1': 'j_20',
        'rssicon1': 'j_21',
        'mobiletextarea1_3': 'j_23',
        'mobilenavbar2_12': 'j_25',
        'donatebutton3': 'j_26',
        'volunteerbutton3': 'j_27'
    };
    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }
    Tiggr.CurrentScreen = 'j_15';
    /*************************
     * NONVISUAL COMPONENTS  *
     *************************/
    var datasources = [];
    // Tiggzi Push-notification registration service
    /************************
     * EVENTS AND HANDLERS  *
     ************************/
    j_15_beforeshow = function() {
        Tiggr.CurrentScreen = 'j_15';
        for (var idx = 0; idx < datasources.length; idx++) {
            datasources[idx].__setupDisplay();
        }
    }
    // screen onload
    screen_0EC5_onLoad = j_15_onLoad = function() {
        screen_0EC5_elementsExtraJS();
        j_15_windowEvents();
        screen_0EC5_elementsEvents();
    }
    // screen window events
    screen_0EC5_windowEvents = j_15_windowEvents = function() {
        $('#j_15').bind('pageshow orientationchange', function() {
            adjustContentHeightWithPadding();
        });
    }
    // screen elements extra js
    screen_0EC5_elementsExtraJS = j_15_elementsExtraJS = function() {
        // screen (screen-0EC5) extra code
    }
    // screen elements handler
    screen_0EC5_elementsEvents = j_15_elementsEvents = function() {
        $("a :input,a a,a fieldset label").live({
            click: function(event) {
                event.stopPropagation();
            }
        });
        $('#j_17 [name="homeicon1"]').die().live({
            click: function() {
                if (!$(this).attr('disabled')) {
                    Tiggr.navigateTo('startScreen', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        });
        $('#j_17 [name="twittericon1"]').die().live({
            click: function() {
                if (!$(this).attr('disabled')) {
                    Tiggr.navigateTo('twitter', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        });
        $('#j_17 [name="rssicon1"]').die().live({
            click: function() {
                if (!$(this).attr('disabled')) {
                    Tiggr.navigateTo('rss', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        });
        $('#j_24 [name="donatebutton3"]').die().live({
            click: function() {
                if (!$(this).attr('disabled')) {
                    window.top.location = 'http://www.cancer.ie/get-involved/fundraise/how-to-donate';
                }
            },
        });
        $('#j_24 [name="volunteerbutton3"]').die().live({
            click: function() {
                if (!$(this).attr('disabled')) {
                    window.top.location = 'http://www.cancer.ie/get-involved/volunteer-with-us';
                }
            },
        });
    }
    $("#j_15").die("pagebeforeshow").live("pagebeforeshow", function(event, ui) {
        j_15_beforeshow();
    });
    if (runBeforeShow) {
        j_15_beforeshow();
    } else {
        j_15_onLoad();
    }
}
$("#j_15").die("pageinit").live("pageinit", function(event, ui) {
    Tiggzi.processSelectMenu($(this));
    j_15_js();
});
